name: Build YACC Project

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y bison flex gcc

      - name: Compile YACC
        run: |
          yacc -d calc.y
          gcc y.tab.c main.c -o calc

      - name: Run YACC Program
        run: ./calc
